### ISSUE TITLE
Please use pinboard's "private" setting

### ISSUE THREAD

**Issue by kannes** [lostsnow/pinboard-firefox#16]
Awesome extension, thank you very much!

Buuuuut: I accidentally posted lots of pins publicly because the extension overrode my "private by default" setting in Pinboard. :(

**Comment by lostsnow** [comment]
Pinboard API did't provider user settings, but you can set `Private checkbox checked by default` in extension option or manually select the `private checkbox`

**Comment by kannes** [comment]
Oh I see, thank you!
