### ISSUE TITLE
Automatically mark all “to read” links as read when you visit the page?

### ISSUE THREAD

**Issue by amandasaurus** [lostsnow/pinboard-firefox#29]
I think that if I have a page bookmarked and marked as “read later” / “to read”, and I visit the page in FF with with extension, then I think it will silently, and automatically mark the link as read! This is not what I would expect!

**Comment by lostsnow** [comment]
Pinboard does not provide "mark as read" API

**Comment by amandasaurus** [comment]
Further investigating tells me that this not from your extension, but a part of pinboard. There's `onmousedown="reg('12345')"` that seems to be triggered when I click the link on the Pinboard website. I presume that's causing this.

I disabled the extension, and the “silently removing read later” was still happening.

**Comment by amandasaurus** [comment]
Silly me! There's a setting in Pinboard for this “Clicking 'toread' items marks them as read”, which I had checked (I think it's the default). I unchecked it, and the problem went away. In case anyone else experiences this problem, that's the solution.
