### ISSUE TITLE
Привет мне нужен файл 

### ISSUE THREAD

**Issue by Arsiprog** [lostsnow/pinboard-firefox#42]
![image](https://github.com/lostsnow/pinboard-firefox/assets/45854657/56ec6604-21e6-44ed-99a9-f3ff36a2e083)
libzkfp.so

Для интеграции ZK9500 с 1С помоги пожалуйста  !

**Comment by Arsiprog** [comment]
![image](https://github.com/lostsnow/pinboard-firefox/assets/45854657/ea37c621-3e0e-4afa-a91f-052a9ce97331)

**Comment by Arsiprog** [comment]
Походу ты удалил проект !

**Comment by Arsiprog** [comment]
моя ветка https://forum.infostart.ru/forum28/topic315116/

**Comment by lostsnow** [comment]
Repository deleted due to DMCA takedown.

**Comment by Arsiprog** [comment]
отправь пожалуйста на почту arsenprog@mail.ru ложили мы на это DMCA

**Comment by Arsiprog** [comment]
Мне  с 1С нужно интегрировать ZK9500

**Comment by Arsiprog** [comment]
Зажал (
