### ISSUE TITLE
Option for Ctrl-D to activate?

### ISSUE THREAD

**Issue by GranoblasticMan** [lostsnow/pinboard-firefox#5]
I really liked Pinboard+ on Chrome because of the ability to remap Ctrl-D to activate the plugin. Is there any way to do this in Firefox?

**Comment by seeba8** [comment]
I played around with it a bit for fun, I did not manage to override the existing keybind, but it is definitely possible to add a new, unused keybind such as alt-p. See here: https://github.com/seeba8/pinboard-firefox/commit/f8d630178218e0dd669c98c292a15c25e2797a05.

**Comment by GranoblasticMan** [comment]
Ah, if overriding the existing command isn't possible, setting a new keybind like that would be good enough for me! =)
