### ISSUE TITLE
Suggested bookmark tags are the same for all pages

### ISSUE THREAD

**Issue by cpeterso** [lostsnow/pinboard-firefox#7]
Regardless of the contents of the page I am pinning, the Pinboard+ popup window's list of suggested tags is always the same: "facebook objective-c twitter ifttt WSH twitterlink 1960s codepo8 Aiviq art".

**Comment by lostsnow** [comment]
The suggest tags using pinboard [suggest API](https://pinboard.in/api/#posts_suggest)

If there is no recommended tags it will return the same data:

```json
[{"popular":["objective-c"]},{"recommended":["ifttt","twitter","facebook","WSH","objective-c","twitterlink","1960s","@codepo8","Aiviq","art"]}]	
```

**Comment by markerikson** [comment]
Could this be reconsidered?  If there are no recommended tags, then the extension ought to recognize that and _not_ show any suggestions at all.

**Comment by jpinnix** [comment]
I actually really like @markerikson's idea here. If you get that default response from Pinboard, then do _not_ show any suggestions at all.
