### ISSUE TITLE
Bookmarked icon color with dark theme

### ISSUE THREAD

**Issue by vayan** [lostsnow/pinboard-firefox#8]
The icon color isn't very visible when using Firefox dark mode, could we do like the RSS Feed icon ? 
White when bookmarked and grey when not?

![screenshot from 2017-06-15 09-37-54](https://user-images.githubusercontent.com/2945291/27170514-76177dfc-51ae-11e7-8f01-94b560f52e91.png)
![screenshot from 2017-06-15 09-37-45](https://user-images.githubusercontent.com/2945291/27170515-761b6372-51ae-11e7-8173-f54b9e68e09c.png)
![screenshot from 2017-06-15 09-37-36](https://user-images.githubusercontent.com/2945291/27170513-76158cae-51ae-11e7-85b7-22cd3594b198.png)

**Comment by pauljacobson** [comment]
I just installed the add-on and noticed this too. I prefer how Pinboard+ works but, on my browser bar, I can barely see the icon.

![screen shot 2017-11-03 at 6 30 48](https://user-images.githubusercontent.com/2912202/32360642-99eef694-c060-11e7-8da0-f6189552ddf2.png)
